version: '2'
services:
  nginx:
    container_name: nginx
    restart: on-faiure:5
    build: nginx/
    ports:
      - "8080:80"
    volumes:
      - /www/static
    volumes_from:
      - server

  database:
    container_name: database
    restart: on-faiure:5
    image: postgres

  server:
    container_name: server
    restart: on-faiure:5
    build: server/
    working_dir: /usr/src/app
    command: sh run.sh
    volumes:
      - ./server:/usr/src/app
      - ./server/static:/usr/src/app/static
    expose:
      - "8000"
    depends_on:
      - database

  client:
    build: ./client
    container_name: client
    restart: on-faiure:5
    volumes:
      - ./client:/usr/src/app
    ports:
      - "8081:4200"
