version: '2'
services:
  nginx:
    container_name: nginx
    restart: on-faiure:5
    build: nginx/
    ports:
      - "8080:80"
    volumes_from:
      - server

  database:
    container_name: database
    restart: on-faiure:5
    image: postgres

  server:
    container_name: server
    restart: on-faiure:5
    build: server/
    volumes:
      - ./server:/usr/src/app
      - ./server/static:/usr/src/app/static
    expose:
      - "8000"
    depends_on:
      - database
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development

  client:
    build:
      context: ./client
      dockerfile: Dockerfile-development
    container_name: client
    restart: on-faiure:5
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/typings
      - /usr/src/app/tmp
      - /usr/src/app/dist
    ports:
      - "8081:4200"
